### ISSUE TITLE
Areas where the bot has locked up for me.

### ISSUE THREAD

**Issue by SongOfTheFates** [Samsterr/sir-squirrel-assistant#21]
Me and a friend have been having issues with the 'Vain Glory' pack's factory event. I got no longs for this one. I just ended up removing 'pride' from f4.

It has frozen on the main menu screen before before it goes to the MD menu, I got no log posts for this one either.

The one I do have log posts for is the 'BP level up' screen. Upon clicking the 'confirm' button it instantly went back to the main menu 'window', so maybe it clicked the 'confirm' button before the BP menu came up. Logs:
2024-10-16 22:44:25,835 - src.mirror - DEBUG - REST STOP: NOT ENOUGH COST, EXITING REST STOP
2024-10-16 22:44:31,531 - src.mirror - INFO - Navigating
2024-10-16 22:44:36,575 - src.mirror - INFO - Selecting Squad for Battle
2024-10-16 22:44:42,755 - src.mirror - INFO - Loading
2024-10-16 22:44:50,081 - src.core - INFO - Starting Battle
2024-10-16 22:48:21,473 - src.core - INFO - Loading
2024-10-16 22:48:26,198 - src.mirror - INFO - Run Won
2024-10-16 22:48:31,047 - src.mirror - INFO - Rewards Claimed
2024-10-16 22:48:32,980 - src.mirror - DEBUG - BP PROMPT
2024-10-16 22:48:35,190 - __main__ - INFO - Run 2
2024-10-16 22:48:35,320 - src.core - INFO - Converting Enkephalin to Modules
2024-10-16 22:48:35,762 - src.core - INFO - Navigating to Mirror Dungeon
2024-10-16 22:48:36,105 - __main__ - INFO - Current Team: poise

Otherwise it's really damn good, thanks for making this. The only thing I'd change is having failed runs not count towards the 'run count', because sometimes you want to target spending x runs, but that's a super minor thing.

**Comment by Samsterr** [comment]
Hi i am actually aware of this and i think identified the issue being that my loading check functions mostly took into account those that have transitional fade to blacks but the one for the rewards claiming at the end to the main menu doesn't have a fade to black. As for the factory packs, i prioritized it to see if i could get more feedback on it due to me testing fixes for it and i think i have more or less fixed the inconsistencies but have not really been able to test it lately. Could you kindly test this hotfix version for me and let me know if you still face these issues
[sirsquirrel.zip](https://github.com/user-attachments/files/17415243/sirsquirrel.zip)

**Comment by SongOfTheFates** [comment]
Thanks! I'll try it and report back tomorrow. I usually just leave it running overnight since I need my PC during the day.

**Comment by SongOfTheFates** [comment]
![limbus lockup](https://github.com/user-attachments/assets/ec464c98-124a-4986-aec8-52caec34d0dc)
Stuck at the rest area, going back and forth. Here's the logs:
2024-10-17 13:04:13,942 - src.core - INFO - Starting Battle
2024-10-17 13:05:10,773 - src.core - INFO - Loading
2024-10-17 13:05:15,999 - src.mirror - INFO - Navigating
2024-10-17 13:05:19,699 - src.mirror - INFO - Entered ? node
2024-10-17 13:05:22,044 - src.mirror - INFO - Rest Stop
2024-10-17 13:05:23,746 - src.mirror - DEBUG - 22.333333333333332
2024-10-17 13:05:25,706 - src.mirror - DEBUG - REST STOP: ENHANCING EGO GIFTS
2024-10-17 13:05:30,561 - src.mirror - INFO - Entered ? node
2024-10-17 13:05:33,298 - src.mirror - INFO - Entered ? node
2024-10-17 13:05:36,021 - src.mirror - INFO - Entered ? node
2024-10-17 13:05:38,728 - src.mirror - INFO - Entered ? node
2024-10-17 13:05:41,449 - src.mirror - INFO - Entered ? node
2024-10-17 13:05:44,181 - src.mirror - INFO - Entered ? node
2024-10-17 13:05:46,904 - src.mirror - INFO - Entered ? node
2024-10-17 13:05:49,653 - src.mirror - INFO - Entered ? node
...
I've removed the rest of it because it just does this for about 30 minutes.

**Comment by Samsterr** [comment]
Thanks for your feedback. I have managed to replicate the issue. Try this one to see if it resolves your issue.
[sirsquirrel.zip](https://github.com/user-attachments/files/17427127/sirsquirrel.zip)

**Comment by SongOfTheFates** [comment]
It locked up on the 'battle pass level screen'. Log:
2024-10-17 23:06:15,638 - src.mirror - INFO - Loading
2024-10-17 23:06:22,979 - src.core - INFO - Starting Battle
2024-10-17 23:10:24,024 - src.core - INFO - Loading
2024-10-17 23:10:28,792 - src.mirror - INFO - Run Won
2024-10-17 23:10:33,611 - src.mirror - INFO - Rewards Claimed
2024-10-17 23:10:35,544 - src.mirror - DEBUG - BP PROMPT
2024-10-17 23:10:35,751 - __main__ - INFO - Run 2
2024-10-17 23:10:35,879 - src.core - INFO - Converting Enkephalin to Modules
2024-10-17 23:10:36,329 - src.core - INFO - Navigating to Mirror Dungeon
2024-10-17 23:10:36,670 - __main__ - INFO - Current Team: poise

There was a level up at the same instance too, maybe that mixed it up?

**Comment by Samsterr** [comment]
hmm. i have accounted for level ups but it doesn't seem to have caught it here. I'm still kinda far away for my next level up so quite hard for me to test as of now. Also do help me test this hotfix which should solve the bp claiming issues hopefully.
[sirsquirrel.zip](https://github.com/user-attachments/files/17437276/sirsquirrel.zip)

**Comment by Samsterr** [comment]
@SongOfTheFates do grab the latest release instead

**Comment by SongOfTheFates** [comment]
I grabbed it, and it doesn't select items at the start anymore. It fails to click on the poise category so it can select items during a new run.

**Comment by Samsterr** [comment]
Can i have the log

**Comment by SongOfTheFates** [comment]
I tried the new .9.7 release in another thread, and the same thing still happens. Here's the final screen, and the log:
2024-10-20 08:10:37,885 - __main__ - INFO - Starting Run
2024-10-20 08:10:37,885 - __main__ - INFO - Run 1
2024-10-20 08:10:38,020 - src.core - INFO - Converting Enkephalin to Modules
2024-10-20 08:10:43,330 - src.core - INFO - Navigating to Mirror Dungeon
2024-10-20 08:10:47,310 - __main__ - INFO - Current Team: sinking
2024-10-20 08:10:50,978 - src.mirror - INFO - E.G.O Gift Selection
It literally just doesn't press LMB once it's over the poise gift category, and it ends up clicking out to the main menu again.
![limbuslockup](https://github.com/user-attachments/assets/ff59b953-a08d-4d09-beb8-8ebe8e9efabf)

**Comment by Samsterr** [comment]
Can i check what resolution is your monitor? Based off your screenshot the dimensions doesnt seem to be 1920x1080

**Comment by SongOfTheFates** [comment]
1440p is the desktop resolution. I'm running Limbus in windowed mode 1080p.

**Comment by Samsterr** [comment]
Ok can i check if this behaviour was only introduced in the later versions? And which was the last version that was working for you?

**Comment by SongOfTheFates** [comment]
Yeah, the earlier versions when I opened my first comment were basically just minor issues; I managed 20 runs after removing the pride pack from f4 one night. I think it was .7 hotfix? I can't remember the exact number.

These last few nights have definitely not been working at all, for a variety of reasons.

I think I'm just going to go with the old .7 hotfix for now, unless you want me to try something out.

**Comment by SongOfTheFates** [comment]
I'm a complete idiot. I forgot to do the whole setting up my team thing again when I replaced it with the .9 version. That's probably why it's not working anymore. Sorry for wasting your time!

**Comment by Samsterr** [comment]
Glad its working for you again no worries. im currently looking to fix some of the clicking issues that cropped up recently so do look out for the hotfix release

**Comment by Samsterr** [comment]
@SongOfTheFates next time theres an update you can just reuse the old config file unless i explicitly mention about needing to change it. i usually repackage the full thing if theres a new image i added and what not

**Comment by SongOfTheFates** [comment]
Yeah, it just completely slipped my mind since I'm usually trying it right before bed when I'm exhausted. 

I'll definitely keep an eye out. Thanks again for taking the time to solve the issues.

**Comment by Samsterr** [comment]
@SongOfTheFates do grab the latest hotfix i put out
